### PR TITLE
Feature/implement streamingcommunity provider

### PR DESCRIPTION
**Pull request by Zanzigu**
Me again!

A few notes:

Unfortunately I had to explicitly tell exoplayer the format of the stream. I added a `type` field to the Video class, to then be used in the playerView to set MimeType.
You may come up with a better idea. Whatever is fine by me.

Also I didn't bother adding Vixcloud to the extractors list as I belive it's a private provider.

### CODE REVIEW

**Review by stantanasi — APPROVED** [review]
Heyy,
I just tested it, sorry for the delay.
Firstly thanks again!!! You are really doing a great job, and I'm very happy to see the app grow!

> Unfortunately I had to explicitly tell exoplayer the format of the stream. I added a type field to the Video class, to then be used in the playerView to set MimeType.

No problem, if you do something that works, I see no problems doing that.

> You may come up with a better idea. Whatever is fine by me.

For something like this, I would maybe try to check the extension of the source URL and give the Mime type corresponding (eg. if the URL ends with .m3u8, then give MimeTypes.APPLICATION_M3U8), but it's totally OK to do like you do and more easy.

> Also I didn't bother adding Vixcloud to the extractors list as I belive it's a private provider.

Totally okay, personnally I always add the extractor inside the extractors list IN CASE someone/something else use it, but it never happens yet lol so 100% okay

**Comment by stantanasi** [comment]
I’m not sure if I configured the repository correctly, but if you want, I let you merge your PR. I’ll create a release as soon as you merge it.

**Comment by Zanzigu** [comment]
> For something like this, I would maybe try to check the extension of the source URL and give the Mime type corresponding (eg. if the URL ends with .m3u8, then give MimeTypes.APPLICATION_M3U8), but it's totally OK to do like you do and more easy.

ExoPlayer already does that. My links NOT ending with the extension in fact made it unable to play

**Comment by Zanzigu** [comment]
> I’m not sure if I configured the repository correctly, but if you want, I let you merge your PR. I’ll create a release as soon as you merge it.

Don't worry, take your time

**Comment by stantanasi** [comment]
> ExoPlayer already does that. My links NOT ending with the extension in fact made it unable to play

Ah okay I understand, so yeah no problem with your solution

**Comment by stantanasi** [comment]
**Done! Available on Release 1.7.3**

**Pull request merged**
